# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: yarn install
    - env:
        GOOGLE_ANALYTICS_GA: ${{ secrets.GOOGLE_ANALYTICS_GA }}
      run: yarn build
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: blog_artifact
        path: blog/.vuepress/dist
        retention-days: 1
