# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  workflow_run:
      workflows: ["Build"]
      branches: [main]
      types: 
        - completed

jobs:
  curl:
    runs-on: ubuntu-latest
    environment: build
    steps:
    - shell: bash
      env:
        DEPLOY_HOOK_URL: ${{ secrets.DEPLOY_HOOK_URL }}
      run: curl "$DEPLOY_HOOK_URL"
